language: python
python:
  - "2.7"
before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.5.zip -nv
- unzip -q google_appengine_1.9.5.zip
script: "./tests.sh"

